<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Report - {{ $date }}</title>
</head>

<body>

    <div class="container">
        <h1>Stock Report - {{ $date }}</h1>

        <h2>Stock Levels</h2>
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Movement Type</th>
                    <th>Quantity</th>
                    <th>Reason</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($stockLevels as $stock)
                    <tr>
                        <td>{{ $stock->product->name }}</td>
                        <td>{{ ucfirst($stock->movement_type) }}</td>
                        <td>{{ $stock->quantity }}</td>
                        <td>{{ $stock->reason }}</td>
                        <td>{{ $stock->created_at }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <h2>Out of Stock Products</h2>
        <ul>
            @foreach ($outOfStockProducts as $product)
                <li>{{ $product->name }}</li>
            @endforeach
        </ul>

        <h2>Low Stock Products</h2>
        <ul>
            @foreach ($lowStockProducts as $product)
                <li>
                    {{ $product->name }} 
                    (Current stock: {{ optional($product->stock)->quantity ?? 'N/A' }})
                </li>
            @endforeach
        </ul>
        
        <ul>
            @foreach ($normalStockProducts as $product)
                <li>
                    {{ $product->name }} 
                    (Current stock: {{ optional($product->stock)->quantity ?? 'N/A' }})
                </li>
            @endforeach
        </ul>        
        
        <div class="stats">
            <div>
                <p>Entry Movements</p>
                <p>{{ $entryStockCount }}</p>
            </div>
            <div>
                <p>Exit Movements</p>
                <p>{{ $exitStockCount }}</p>
            </div>
            <div>
                <p>Adjustment Movements</p>
                <p>{{ $adjustmentStockCount }}</p>
            </div>
        </div>

        <div class="footer">
            <p>Generated by <a href="#">Administrateur</a> | {{ $date }}</p>
        </div>
    </div>

</body>

</html>
